node 14.0 also cannot install a working webpack-cli
Error (from CI run) is:

    > webpack --config test/webpack/webpack.config.js && node test/webpack/dist/bundle.js # requires Node.js >=10.8, >=12.?

    [webpack-cli] Error: Cannot find module 'ajv/dist/compile/codegen'
    Require stack:
    - /home/runner/work/require-in-the-middle/require-in-the-middle/node_modules/ajv-keywords/dist/definitions/typeof.js
    - /home/runner/work/require-in-the-middle/require-in-the-middle/node_modules/ajv-keywords/dist/keywords/typeof.js
    ...